name: Run tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: 3.10 EOL coming soon, remove it from matrix once support is dropped
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv pip install --system -r requirements.txt pytest pytest-cov

      - name: Test with pytest
        run: |
          pytest --cov=. --cov-report=xml tests/test_validate.py
          pytest --cov=. --cov-report=xml tests/test_score.py
